env:                      "local"
postgresConnStr:          "postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable"
postgresConnStrForDocker: "postgresql://postgres:postgres@db:5432/postgres?sslmode=disable"
grpc:  
  port:                   50051  
  timeout:                10h
